- project_name: math-ce1
  organization_unit: educations
  owner_name: owner-1
  reviewers:
    code_review:
      - reviewer-1
  job_name: design_usecase
  mission_type: design_usecase
  runtime_variables:
    usecase: math_question_generator