name: 'Windows Preparation'
description: 'Windows Preparation For Running xia-gpt'
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.11

    - name: Install dependencies
      shell: pwsh
      run: |
        python -m pip install -r requirements.txt
        python -m pip install -r requirements-dev.txt
        python -m pip install -r requirements-xia.txt
