- project_name: hello-world
  organization_unit: demo
  owner_name: owner-1
  job_name: init-project
  campaign_type: software/python/simple/create
  input_contexts:
    workspace/original_requirements: Create a program to print "Hello World".
