stages:
  - check

check_env_variable:
  stage: check
  when: manual
  script:
    - |
      if [ -z "$GITLAB_TOKEN" ]; then
        echo "Error: Environment variable GITLAB_TOKEN is not set"
        exit 1
      else
        echo "GITLAB_TOKEN is set!"
      fi
    - |
      GITLAB_HOST=${GITLAB_HOST:-"gitlab.com"}
      GROUP_NAME=$(grep '^name: ' config/company.yaml | cut -d' ' -f2)
      GITLAB_ENDPOINT="https://${GITLAB_HOST}/api/v4/groups/${GROUP_NAME}"
      RESPONSE_CODE=$(curl --write-out "%{http_code}" --silent --output /dev/null -H "Private-Token: $TOKEN" $GITLAB_ENDPOINT)
      if [ "$RESPONSE_CODE" = "200" ]; then
        echo "The top-level group $GROUP_NAME exists."
      else
        echo "The top-level group $GROUP_NAME does not exist on ${GITLAB_HOST} or it's private and the token doesn't have the necessary permissions."
        echo "Please create the top-level group $GROUP_NAME on ${GITLAB_HOST} and check the given token's permissions"
        echo "The top-level group is used for representing the company. You could change the group name by modify the name field in the file `config/company.yaml` "
        exit 1
      fi
    - |
      if [ -z "$OPENAI_API_KEY" ]; then
        echo "Error: Environment variable OPENAI_API_KEY is not set"
        exit 1
      else
        echo "OPENAI_API_KEY is set!"
      fi
