stages:
  - check

check_env_variable:
  stage: check
  when: manual
  script:
    - |
      if [ -z "$GITLAB_TOKEN" ]; then
        echo "Error: Environment variable GITLAB_TOKEN is not set"
        exit 1
      else
        echo "GITLAB_TOKEN is set!"
      fi
    - |
      GROUP_NAME=$(grep '^name: ' config/company.yaml | cut -d' ' -f2)
      GITLAB_ENDPOINT="https://gitlab.com/api/v4/groups/${GROUP_NAME}"
      RESPONSE_CODE=$(curl --write-out "%{http_code}" --silent --output /dev/null -H "Private-Token: $TOKEN" $GITLAB_ENDPOINT)
      if [ "$RESPONSE_CODE" = "200" ]; then
        echo "The group $GROUP_NAME exists."
      else
        echo "The group $GROUP_NAME does not exist or it's private and the token doesn't have the necessary permissions."
      fi
    - |
      if [ -z "$OPENAI_API_KEY" ]; then
        echo "Error: Environment variable OPENAI_API_KEY is not set"
        exit 1
      else
        echo "OPENAI_API_KEY is set!"
      fi
