- project_name: hello-world
  organization_unit: demos
  owner_name: owner-1
  job_name: init-graphic
  campaign_type: graphic/pollination/create
  runtime_variables:
    filename: home.png
  input_contexts:
    workspace/original_requirements: painting of a depressed robot.
