title: X-I-A
name: xia-company
visibility: public
organization:
  executives: {}
  functional_departments:
    human_resources: {}
    marketing: {}
  product_sectors:
    games: {}
    utilities: {}
    web_apps: {}
    mobile_apps: {}
