- project_name: robot-rumble-arena
  organization_unit: games
  owner_name: owner-1
  reviewers:
    code_review:
      - reviewer-1
  job_name: init-project
  campaign_type: software_initialization
  input_contexts:
    requirements/original_requirements: Create a game whose name is `Robot Rumble Arena`. Build and customize your robot, then enter the arena for explosive one-on-one battles against other mechanical gladiators.
