- project_name: galactic-pizza-delivery
  organization_unit: games
  owner_name: owner-1
  job_name: init-project
  campaign_type: software_initialization
  input_contexts:
    requirements/original_requirements: Create a game whose name is `Galactic Pizza Delivery`. Race against the clock to deliver interstellar pizzas across the galaxy while dodging asteroids and space pirates.
