name: Windows Run Initial

on:
  workflow_dispatch:

jobs:
  run_windows_initial:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Environment Preparations
      uses: ./.github/actions/windows-preparation
