name: Windows Replay Mission

on:
  workflow_dispatch:

jobs:
  run_windows_replay_mission:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Environment Preparations
      uses: ./.github/actions/windows-preparation

    - name: Run Application
      run: python main.py --skip-sync-company -n 2