name: Windows Replay Project

on:
  workflow_dispatch:

jobs:
  run_windows_replay_project:
    runs-on: windows-latest
    env:
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Environment Preparations
      uses: ./.github/actions/windows-preparation

    - name: Run Application
      run: python main.py --skip-sync-company --recreate-actors --recreate-projects -n 4